Sprint1
oier-elorrieta/E3_T6_PROG_GI pull request #2
Opened 2024-02-05 17:56 UTC by Markel05

**Dena euskaratuta eta berreginda objektu guztiekin klasean esan bezala.**

2024-02-06 08:57 UTC, oier-elorrieta requested changes
Ez dut test-ik ikusten eta ikusten ditut sprint1-ean eskatzen ez diren JFrame-ak.
Test-ik gabe ezin da pull request onartu.
Erantzun egindako galderei, mesedez.

2024-02-06 08:57 UTC, oier-elorrieta commented on src/model/Aretoa.java
> +
Zertarako behar dituzue saioak aretoan? Posible litzateke datu basean 20 saio baino gehiago egotea areto horretan?

2024-02-06 08:57 UTC, oier-elorrieta commented on src/model/Karteldegia.java
> +	public Filma[] filmaList = new Filma[20];
20 baino filme gehiago egon daitezke? Nola kontrolatuko duzue hori?

2024-02-06 08:57 UTC, oier-elorrieta commented on src/model/Ticket.java
> +	public Ticket() {
Zertarako erabiltzen duzue konstruktore hau?

2024-02-06 08:57 UTC, oier-elorrieta commented on src/model/Ticket.java
> +	private Saioa saioa;
Ezin dira sarrerak erosi saio bat baino gehiagorako? APP-ean esango nuke baietz....

2024-02-06 10:40 UTC, Markel05 commented on src/model/Ticket.java
> +	public Ticket() {
Ezabatuta

2024-02-06 10:44 UTC, Markel05 commented on src/model/Karteldegia.java
> +	public Filma[] filmaList = new Filma[20];
"20" hori adibide bezala jarri dugu, momentuz. Arrayaren tamaina datu basetik hartuko dugu SELECT count batekin.

2024-02-06 10:44 UTC, Markel05 commented on src/model/Aretoa.java
> +
"20" hori adibide bezala jarri dugu, momentuz. Arrayaren tamaina datu basetik hartuko dugu SELECT count batekin.

2024-02-06 10:50 UTC, Markel05 commented on src/model/Aretoa.java
> +
Saioarena, kendu dugu SaioList. Zineman daukagunez SaioList, uste dugu aretoan ez dugula behar.

2024-02-06 11:05 UTC, Markel05 commented on src/model/Ticket.java
> +	private Saioa saioa;
Saioa ArrayList bihurtu dugu eta, orain, hainbat sarrera saio berdinerako edo beste saio batzuetarako ticket berdinarako egon ahal dira.

2024-02-06 11:06 UTC, Markel05 commented on src/model/Ticket.java
> +	public Ticket() {
Programa hasieratzean Ticket objektua sortuko da balio gabe, eta pelikulak sartu ahala, Setters-ekin balioak gehitzen joango gara.

2024-02-08 10:59 UTC, oier-elorrieta approved these changes

2024-02-08 10:59 UTC, oier-elorrieta commented on src/model/Ticket.java
> +public class Ticket {
Grrr. Oso konforme ez, baina honengatik ez zaituztet trinkatuta utziko.

2024-02-08 11:05 UTC, OierZub approved these changes

2024-02-08 11:19 UTC, merged