Sprint2
oier-elorrieta/E3_T6_PROG_GI pull request #3
Opened 2024-02-22 09:56 UTC by Markel05

2024-02-22 11:49 UTC, OierZub requested changes

2024-02-22 11:49 UTC, OierZub commented on src/model/sql/ConexioaSQL.java
> +	public static void conexioaIrekiEtaItxi() {
Metodoaren izena ez da logikoa.

2024-02-22 11:49 UTC, OierZub commented on src/model/metodoak/Metodoak.java
> +public class Metodoak {
Izen hau ez da esanguratzua.

2024-02-22 12:55 UTC, EkaitzB commented on src/model/sql/ConexioaSQL.java
> +	public static void conexioaIrekiEtaItxi() {
Izena aldatuta (datuakKargatu)

2024-02-22 12:56 UTC, EkaitzB commented on src/model/metodoak/Metodoak.java
> +public class Metodoak {
Izena aldatuta (JFrameSortu)

2024-02-23 10:46 UTC, oier-elorrieta commented
s

2024-02-23 10:47 UTC, oier-elorrieta approved these changes
Oneritzia

2024-02-23 10:50 UTC, OierZub approved these changes

2024-02-23 10:50 UTC, merged